name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # Single-page apps need a 404 that routes to index for deep links
      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      # Disable Jekyll so GitHub Pages serves asset paths as-is
      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: frontend/dist